import { Language } from './types';

export const translations = {
  zh: {
    appName: "水云",
    onboardingTitle: "初次见面",
    onboardingSubtitle: "请留下您的雅号与容颜",
    nickname: "昵称",
    avatar: "头像",
    enter: "开启书志",
    myBooks: "我的书志",
    addBook: "添加书籍",
    bookTitle: "书名",
    bookDescription: "简介",
    bookCover: "封面",
    save: "保存",
    cancel: "取消",
    community: "社区",
    read: "共读",
    reread: "重温",
    activities: "活动",
    participate: "参与",
    forward: "转发",
    comment: "评论",
    like: "赞",
    writeEntry: "撰写篇章",
    entryTitle: "标题",
    entryContent: "内容",
    entryFeelings: "感悟",
    takePhoto: "拍照",
    manualInput: "手动输入",
    switchLang: "English",
    noBooks: "暂无书籍，开启您的第一本吧",
    announcement: "公告",
    nicknameRequired: "请输入昵称",
    participateSuccess: "参与成功",
    forwardToCommunity: "转发至社区",
    selectModule: "选择模块",
    addActivity: "发起活动",
    activityTitle: "活动标题",
    activityAnnouncement: "活动内容",
    activityLocation: "活动地点",
    activityTime: "活动时间",
    activityPosters: "活动海报",
    uploadPoster: "上传海报",
    pastActivities: "往期活动",
    upcomingActivities: "即将开始",
    annotate: "批注",
    sentenceAnnotations: "逐句批注",
    addAnnotation: "添加批注",
    shareToCommunity: "一键分享至社区",
    activityShared: "活动已分享至社区",
    userHome: "用户主页",
    readingBooks: "正在阅读",
    userAbstracts: "个人文摘",
    persistenceWarning: "提示：当前为临时存储模式，数据可能在系统维护时重置。建议定期导出备份。",
    exportData: "导出数据备份",
    saving: "正在保存...",
    profile: "个人中心",
    preview: "预览",
    pinned: "置顶",
    postPreview: "发布预览",
    share: "分享",
  },
  en: {
    appName: "WaterCloud",
    onboardingTitle: "First Meeting",
    onboardingSubtitle: "Please leave your nickname and avatar",
    nickname: "Nickname",
    avatar: "Avatar",
    enter: "Start Journal",
    myBooks: "My Journals",
    addBook: "Add Book",
    bookTitle: "Title",
    bookDescription: "Description",
    bookCover: "Cover",
    save: "Save",
    cancel: "Cancel",
    community: "Community",
    read: "Read",
    reread: "Reread",
    activities: "Activities",
    participate: "Join",
    forward: "Share",
    comment: "Comment",
    like: "Like",
    writeEntry: "Write Entry",
    entryTitle: "Title",
    entryContent: "Content",
    entryFeelings: "Feelings",
    takePhoto: "Camera",
    manualInput: "Input",
    switchLang: "简体中文",
    noBooks: "No books yet, start your first one",
    announcement: "Announcement",
    nicknameRequired: "Nickname required",
    participateSuccess: "Joined successfully",
    forwardToCommunity: "Share to Community",
    selectModule: "Select Module",
    addActivity: "Host Activity",
    activityTitle: "Activity Title",
    activityAnnouncement: "Activity Content",
    activityLocation: "Location",
    activityTime: "Time",
    activityPosters: "Posters",
    uploadPoster: "Upload Poster",
    pastActivities: "Past Activities",
    upcomingActivities: "Upcoming",
    annotate: "Annotate",
    sentenceAnnotations: "Sentence Annotations",
    addAnnotation: "Add Annotation",
    shareToCommunity: "Share to Community",
    activityShared: "Activity shared to community",
    userHome: "User Profile",
    readingBooks: "Reading",
    userAbstracts: "Abstracts",
    persistenceWarning: "Note: Temporary storage mode. Data may reset during maintenance. Export backups regularly.",
    exportData: "Export Backup",
    saving: "Saving...",
    profile: "Profile",
    preview: "Preview",
    pinned: "Pinned",
    postPreview: "Post Preview",
    share: "Share",
  }
}
;
